spring:
  datasource:
    username: root
    password: paigu000
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:*:mybatis/*.xml
